export type CurrentMovie = {
    backdrop_path: string,
    id: number,
    title?: string,
    original_title?: string,
    name?: string,
    original_name?: string,
    overview: string
    poster_path: string,
    media_type: string,
    adult: boolean,
    original_language: string,
    genre_ids?: number[],
    popularity: number,
    first_air_date?: string,
    vote_average: number,
    vote_count: number,
    origin_country?: string[],
}

export type GameStat = {
    added: number,
    added_by_status: {
        beaten: number,
        dropped: number,
        owned: number,
        playing: number,
        toplay: number,
        yet: number,
    }, 
    background_image: string,
    clip: null,
    dominant_color: string,
    esrb_rating: {
        id: number,
        name: string,
        slug: string,
    }, 
    genres: Object[],
    id: number,
    metacritic: number,
    name: string,
    parent_platforms: Object[],
    platforms: Object[],
    playtime: number,
    rating: number,
    rating_top: number,
    ratings: Object[],
    ratings_count: number,
    released: string,
    reviews_count: number,
    reviews_text_count: number,
    saturated_color: string,
    short_screenshots: Object[],
    slug: string,
    stores: Object[],
    suggestions_count: number,
    tags: Object[],
    tba: boolean,
    updated: string,
    user_game: null,
}

// export type movie = {
//     adult: boolean,
//     backdrop_path: string,
//     genre_ids: number[],
//     id: number,
//     media_type: string,
//     original_language: string,
//     original_title: string,
//     overview: string,
//     popularity: number,
//     poster_path: string,
//     release_date: string,
//     title: string,
//     video: false,
//     vote_average: number,
//     vote_count: number,
// }