export type GameStat = {
    added: number,
    added_by_status: {
        beaten: number,
        dropped: number,
        owned: number,
        playing: number,
        toplay: number,
        yet: number,
    }, 
    background_image: string,
    clip: null,
    dominant_color: string,
    esrb_rating: {
        id: number,
        name: string,
        slug: string,
    }, 
    genres: Object[],
    id: number,
    metacritic: number,
    name: string,
    parent_platforms: Object[],
    platforms: Object[],
    playtime: number,
    rating: number,
    rating_top: number,
    ratings: Object[],
    ratings_count: number,
    released: string,
    reviews_count: number,
    reviews_text_count: number,
    saturated_color: string,
    short_screenshots: Object[],
    slug: string,
    stores: Object[],
    suggestions_count: number,
    tags: Object[],
    tba: boolean,
    updated: string,
    user_game: null,
}

